### ISSUE TITLE
Load vault item created in test recipe

### ISSUE THREAD

**Issue by miguelaferreira** [chef-cookbooks/chef-vault#33]
I've created a vault and an item following the example of this cookbook.
I'm creating a vault item that needs to be loaded in the same chef-run (that's why I'm creating it in the first place).
However, I can't load it after creation since the client key used by chef-client is not the same that I used to sign the vault.

To make it more concrete, let's imagine that the we need to load the 'clean-energy' item from the 'green' data bag as created here: https://github.com/opscode-cookbooks/chef-vault/blob/master/test/fixtures/cookbooks/test/recipes/chef_vault_secret.rb

In my case, when chef-client hits the `ChefVault::Item.load('green', 'clean-energy')` line, it errors out because the keys do not match. I mean the vault item was signed with the key of 'hydroelectric', but that is not the same as the client key of the current chef-client.

I've tried to use the `clients` and `search` attributes of the `chef_vault_secret` to include the client key of the node that is running chef-client, but that always seems to produce no good results.

**Comment by karthik-altiscale** [comment]
Hi. Are there any updates on this. I am still facing the error.  I get, 
```
ChefVault::Exceptions::SecretDecryption: green/clean-energy is not encrypted with your public key
```

**Comment by miguelaferreira** [comment]
maybe @smurawski can help get some attention to this?

**Comment by c240amg** [comment]
having the same issue with vagrant/kitchen converges 
have a vault in my /data_bags directory (specified in knife.rb)
but a chef-client run gives me.
data-vault/1 is not encrypted with your public key.  Contact an administrator of the vault item to encrypt for you!

**Comment by bheuvel** [comment]
Kinda got it working, but first interesting to see how your _vaultbag_ _keys.json looks like. For me it would be:
```json
{
  "id": "somevaultname_keys",
  "admins": [
   ],
  "clients": [
  ],
  "search_query": "*:*",
  "": "upAndManyMoreKeyCharactersDeletedForReadability:)4A==\n"
}
```
Problem which is created here, is that the "real" databag's encryption key has been encrypted with the public key of the respective client (so far so good). Only problem is that this client is named: `""` (empty string).

The code where it seems to go wrong is in the gem [line 24](https://github.com/Nordstrom/chef-vault/blob/master/lib/chef-vault/chef_patch/api_client.rb#L24): `if response.is_a?(Chef::ApiClient)`.

In combination with a "real" Chef server, this returns `true`, with chef-zero it returns `false`.
As code assumes it's not an ApiClient, it creates a new ApiClient object and gets the name from the node attribute `clientname`, which does not exist, resulting in an empty string.

Encryption and all continues, and the (empty) clientname is written to the list.
At point of when decryption needs to be done, current client is searched in that list, and conclusion is drawn that (some)other client has access, no not this named client.

So the actual problem is `http_api.get` not returning the proper object type, resulting in a fallback scenario(!)

Problem there is the client not having `clientname` attribute, but that you can fix by adding this to the json file of the client.

**Comment by bheuvel** [comment]
Apparently fixed in latest version of Chef-Zero: https://github.com/chef/chef-zero/blame/2b239ae9f4d32e48f3806824e9317d74d77fbb7f/lib/chef_zero/chef_data/data_normalizer.rb#L19

**Comment by karthik-altiscale** [comment]
I got it working and created a minimal example cookbook 
https://github.com/karthik-altiscale/chef-vault_kitchen_spec

**Comment by cheeseplus** [comment]
Given the chef-zero bug resolution and example, closing this one.
